@localhost = http://127.0.0.1:3000/game/
@contentType = application/json

###SAMPLE_GET
POST {{localhost}}SAMPLE_GET
Content-Type: {{contentType}}

{
    
}


###INSERT_EMP_ID_WHEN_GAME_STARTS
POST {{localhost}}INSERT_EMP_ID_WHEN_GAME_STARTS
Content-Type: {{contentType}}

{
    "emp_login_id":"AG0056", 
    "created_by":1
}



###UPDATE_GAME_COMPLETION_TIME
POST {{localhost}}UPDATE_GAME_COMPLETION_TIME
Content-Type: {{contentType}}

{
    "emp_login_id":"AG0056", 
   "game_completion_time_in_sec":1, 
   "updated_by":1
}


###UPDATE_CHEAT_CODE_ATTEMPT_AND_TIME
POST {{localhost}}UPDATE_CHEAT_CODE_ATTEMPT_AND_TIME
Content-Type: {{contentType}}

{
    "emp_login_id":"AG0056", 
    "cheat_code_attempt":1, 
    "cheat_code_time":"2025-09-20 04:30:51", 
    "updated_by":"AG0056"
}

###GET_TOP_PLAYERS_FOR_LEADER_BOARD

POST {{localhost}}GET_TOP_PLAYERS_FOR_LEADER_BOARD
Content-Type: {{{{contentType}}}}